// src/navigation/config/linkingConfig.js
export const linkingConfig = {
  screens: {
    Login: 'login',
    BottomTabs: {
      path: '',
      screens: {
        Home: 'home',
        Orders: 'orders',
        Scan: 'scan',
        Parts: 'partstab',
        Profile: 'profile',
      },
    },
    ComplaintsTopNavigation: {
      path: 'complaints',
      parse: {
        tab: (tab) => tab || 'all',
      },
    },
    SparePartScreen: 'spare',
    PartDetails: 'part/:partId',
    ComplaintDetail: 'complaint/:complaintId',
    MyComplaints: 'mycomplaints',
    Bucket: 'bucket',
    BucketpartDetails: 'bucketpart/:partId',
    AddPart: 'addpart',
    AMC: 'amc',
    AMCDetails: 'amcdetails/:amcId',
    AMCList: 'amclist',
    MyAmc: 'myamc',
    CompleteAMCDetails: 'completeamc/:amcId',
    PreBooking: 'prebooking',
    PayOut: 'payout',
    NotificationTopNavigation: 'notifications',
    Password: 'password',
    ReplaceParts: 'replaceparts',
    TermsConditions: 'terms',
    Support: 'support',
    Billing: 'billing/:billId',
    AddPartBilling: 'addpartbilling',
    Remarkscreen: 'remark/:remarkId',
    ProductDetails: 'product/:productId',
    QRCodes: 'qrcodes',
    QRCodeDetails: 'qrcode/:qrId',
    Services: 'services',
    ProfileDetails: 'profiledetails',
  },
};